import type { Pecera, Filtro, Fish } from './types'

export function formatColones(price: number): string {
  return `₡${price.toLocaleString('es-CR', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
}

export const PECERAS: Pecera[] = [
  {
    id: 'nano-20',
    name: 'Nano 20L',
    litros: 20,
    dimensions: '40 × 25 × 25 cm',
    price: 18000,
    image: 'nano 20L.png',
  },
  {
    id: 'estandar-60',
    name: 'Estándar 60L',
    litros: 60,
    dimensions: '60 × 35 × 35 cm',
    price: 35000,
    image: 'pecera_60.jpg',
  },
  {
    id: 'mediana-120',
    name: 'Mediana 120L',
    litros: 120,
    dimensions: '90 × 40 × 40 cm',
    price: 65000,
    image: 'pecera_120.png',
  },
  {
    id: 'grande-200',
    name: 'Grande 200L',
    litros: 200,
    dimensions: '120 × 50 × 40 cm',
    price: 95000,
    image: 'pecera_grande_200.jpg',
  },
  {
    id: 'xl-300',
    name: 'XL 300L',
    litros: 300,
    dimensions: '150 × 60 × 45 cm',
    price: 150000,
    image: 'pecera_XL_300.jpg',
  },
]

export const FILTROS: Filtro[] = [
  {
    id: 'mini',
    name: 'Filtro Mini',
    tipo: 'Interno',
    minLitros: 0,
    maxLitros: 30,
    price: 9500,
    image: 'Filtro.png',
  },
  {
    id: 'interno',
    name: 'Filtro Interno',
    tipo: 'Interno',
    minLitros: 20,
    maxLitros: 80,
    price: 14500,
    image: 'filtro-interno.png',
  },
  {
    id: 'externo-m',
    name: 'Filtro Externo M',
    tipo: 'Externo',
    minLitros: 60,
    maxLitros: 150,
    price: 28000,
    image: 'filtro-externo.png',
  },
  {
    id: 'externo-l',
    name: 'Filtro Externo L',
    tipo: 'Externo',
    minLitros: 120,
    maxLitros: 250,
    price: 45000,
    image: 'filtro-externo-L.png',
  },
  {
    id: 'sump',
    name: 'Filtro Sump',
    tipo: 'Sump',
    minLitros: 200,
    maxLitros: Infinity,
    price: 75000,
    image: 'filtro-sump.png',
  },
]

export const PECES: Fish[] = [
  // --- AGUA DULCE ---
  {
    id: 'betta',
    name: 'Betta',
    waterType: 'dulce',
    temperament: 'solitario',
    maxQuantity: 1,
    price: 3500,
    description: 'Pez de cola larga y colores vibrantes. Muy territorial, debe vivir solo.',
    incompatibleWith: ['guppy', 'neon-tetra', 'angel'],
    image: 'Betta.png',
  },
  {
    id: 'neon-tetra',
    name: 'Neón Tetra',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 15,
    price: 800,
    description: 'Pequeño pez de banco con franja azul y roja. Ideal en grupos.',
    incompatibleWith: ['betta', 'angel', 'oscar'],
    image: 'Neon Tetra.png',
  },
  {
    id: 'guppy',
    name: 'Guppy',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 12,
    price: 600,
    description: 'Colorido y resistente, perfecto para principiantes.',
    incompatibleWith: ['betta', 'oscar'],
    image: 'Guppy.png',
  },
  {
    id: 'goldfish',
    name: 'Pez Dorado',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 5,
    price: 1200,
    description: 'Clásico pez de agua fría. Requiere espacio y buena filtración.',
    incompatibleWith: ['betta', 'oscar', 'angel'],
    image: 'goldfish.png',
  },
  {
    id: 'angel',
    name: 'Pez Ángel',
    waterType: 'dulce',
    temperament: 'semiagresivo',
    maxQuantity: 4,
    price: 2500,
    description: 'Elegante pez triangular. Puede perseguir peces pequeños.',
    incompatibleWith: ['neon-tetra', 'guppy', 'goldfish', 'betta'],
    image: 'angel.png',
  },
  {
    id: 'pleco',
    name: 'Plecostomo',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 2,
    price: 2000,
    description: 'Limpiador natural del acuario. Se alimenta de algas en el fondo.',
    incompatibleWith: [],
    image: 'pleco.png',
  },
  {
    id: 'corydoras',
    name: 'Corydoras',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 8,
    price: 900,
    description: 'Pequeño pez de fondo muy social, vive mejor en grupos de 4+.',
    incompatibleWith: ['oscar'],
    image: 'corydoras.png',
  },
  {
    id: 'oscar',
    name: 'Oscar',
    waterType: 'dulce',
    temperament: 'agresivo',
    maxQuantity: 2,
    price: 4500,
    description: 'Pez grande y territorial. Requiere pecera amplia y pocos compañeros.',
    incompatibleWith: ['neon-tetra', 'guppy', 'corydoras', 'angel', 'goldfish'],
    image: 'oscar.png',
  },

  // --- AGUA SALADA ---
  {
    id: 'clownfish',
    name: 'Pez Payaso',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 2,
    price: 8500,
    description: 'Icónico pez naranja y blanco. Vive en simbiosis con anémonas.',
    incompatibleWith: ['damsel', 'lionfish'],
    image: 'clownfish.png',
  },
  {
    id: 'damsel',
    name: 'Doncella Azul',
    waterType: 'salada',
    temperament: 'agresivo',
    maxQuantity: 3,
    price: 4500,
    description: 'Brillante azul eléctrico. Muy territorial con sus congéneres.',
    incompatibleWith: ['clownfish', 'marine-angel', 'neon-goby', 'chromis'],
    image: 'damsel.png',
  },
  {
    id: 'marine-angel',
    name: 'Ángel Marino',
    waterType: 'salada',
    temperament: 'semiagresivo',
    maxQuantity: 2,
    price: 12000,
    description: 'Espectacular pez con franjas de colores. Necesita espacio y escondites.',
    incompatibleWith: ['damsel'],
    image: 'marine-angel.png',
  },
  {
    id: 'tang',
    name: 'Tang Azul',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 1,
    price: 15000,
    description: 'El famoso pez de aleta caudal amarilla. Necesita nadar mucho.',
    incompatibleWith: [],
    image: 'tang.png',
  },
  {
    id: 'neon-goby',
    name: 'Gobio Neón',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 6,
    price: 3500,
    description: 'Pequeño limpiador con franja azul fluorescente. Muy activo.',
    incompatibleWith: ['damsel', 'lionfish'],
    image: 'neon-goby.png',
  },
  {
    id: 'mandarin',
    name: 'Pez Mandarina',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 2,
    price: 9000,
    description: 'Uno de los peces más coloridos del mundo. Dieta especializada.',
    incompatibleWith: ['lionfish'],
    image: 'mandarin.png',
  },
  {
    id: 'lionfish',
    name: 'Pez León',
    waterType: 'salada',
    temperament: 'predador',
    maxQuantity: 1,
    price: 18000,
    description: 'Depredador de espinas venenosas. Solo puede coexistir con peces grandes.',
    incompatibleWith: ['clownfish', 'neon-goby', 'mandarin', 'chromis', 'damsel'],
    image: 'lionfish.png',
  },
  {
    id: 'chromis',
    name: 'Chromis Verde',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 8,
    price: 2500,
    description: 'Pez de banco resistente y activo. Excelente para acuarios de arrecife.',
    incompatibleWith: ['lionfish', 'damsel'],
    image: 'chromis.png',
  },
]
