import type { Pecera, Filtro, Fish } from './types'

export function formatColones(price: number): string {
  return `₡${price.toLocaleString('es-CR', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
}

export const PECERAS: Pecera[] = [
  {
    id: 'nano-20',
    name: 'Nano 20L',
    litros: 20,
    dimensions: '40 × 25 × 25 cm',
    price: 18000,
    image: 'nano 20L.png',
  },
  {
    id: 'estandar-60',
    name: 'Estándar 60L',
    litros: 60,
    dimensions: '60 × 35 × 35 cm',
    price: 35000,
  },
  {
    id: 'mediana-120',
    name: 'Mediana 120L',
    litros: 120,
    dimensions: '90 × 40 × 40 cm',
    price: 65000,
  },
  {
    id: 'grande-200',
    name: 'Grande 200L',
    litros: 200,
    dimensions: '120 × 50 × 40 cm',
    price: 95000,
  },
  {
    id: 'xl-300',
    name: 'XL 300L',
    litros: 300,
    dimensions: '150 × 60 × 45 cm',
    price: 150000,
  },
]

export const FILTROS: Filtro[] = [
  {
    id: 'mini',
    name: 'Filtro Mini',
    tipo: 'Interno',
    minLitros: 0,
    maxLitros: 30,
    price: 9500,
    image: 'Filtro.png',
  },
  {
    id: 'interno',
    name: 'Filtro Interno',
    tipo: 'Interno',
    minLitros: 20,
    maxLitros: 80,
    price: 14500,
  },
  {
    id: 'externo-m',
    name: 'Filtro Externo M',
    tipo: 'Externo',
    minLitros: 60,
    maxLitros: 150,
    price: 28000,
  },
  {
    id: 'externo-l',
    name: 'Filtro Externo L',
    tipo: 'Externo',
    minLitros: 120,
    maxLitros: 250,
    price: 45000,
  },
  {
    id: 'sump',
    name: 'Filtro Sump',
    tipo: 'Sump',
    minLitros: 200,
    maxLitros: Infinity,
    price: 75000,
  },
]

export const PECES: Fish[] = [
  // --- AGUA DULCE ---
  {
    id: 'betta',
    name: 'Betta',
    waterType: 'dulce',
    temperament: 'solitario',
    maxQuantity: 1,
    price: 3500,
    description: 'Pez de cola larga y colores vibrantes. Muy territorial, debe vivir solo.',
    incompatibleWith: ['guppy', 'neon-tetra', 'angel'],
  },
  {
    id: 'neon-tetra',
    name: 'Neón Tetra',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 15,
    price: 800,
    description: 'Pequeño pez de banco con franja azul y roja. Ideal en grupos.',
    incompatibleWith: ['betta', 'angel', 'oscar'],
  },
  {
    id: 'guppy',
    name: 'Guppy',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 12,
    price: 600,
    description: 'Colorido y resistente, perfecto para principiantes.',
    incompatibleWith: ['betta', 'oscar'],
    image: 'Guppy.png',
  },
  {
    id: 'goldfish',
    name: 'Pez Dorado',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 5,
    price: 1200,
    description: 'Clásico pez de agua fría. Requiere espacio y buena filtración.',
    incompatibleWith: ['betta', 'oscar', 'angel'],
  },
  {
    id: 'angel',
    name: 'Pez Ángel',
    waterType: 'dulce',
    temperament: 'semiagresivo',
    maxQuantity: 4,
    price: 2500,
    description: 'Elegante pez triangular. Puede perseguir peces pequeños.',
    incompatibleWith: ['neon-tetra', 'guppy', 'goldfish', 'betta'],
  },
  {
    id: 'pleco',
    name: 'Plecostomo',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 2,
    price: 2000,
    description: 'Limpiador natural del acuario. Se alimenta de algas en el fondo.',
    incompatibleWith: [],
  },
  {
    id: 'corydoras',
    name: 'Corydoras',
    waterType: 'dulce',
    temperament: 'pacifico',
    maxQuantity: 8,
    price: 900,
    description: 'Pequeño pez de fondo muy social, vive mejor en grupos de 4+.',
    incompatibleWith: ['oscar'],
  },
  {
    id: 'oscar',
    name: 'Oscar',
    waterType: 'dulce',
    temperament: 'agresivo',
    maxQuantity: 2,
    price: 4500,
    description: 'Pez grande y territorial. Requiere pecera amplia y pocos compañeros.',
    incompatibleWith: ['neon-tetra', 'guppy', 'corydoras', 'angel', 'goldfish'],
  },

  // --- AGUA SALADA ---
  {
    id: 'clownfish',
    name: 'Pez Payaso',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 2,
    price: 8500,
    description: 'Icónico pez naranja y blanco. Vive en simbiosis con anémonas.',
    incompatibleWith: ['damsel', 'lionfish'],
  },
  {
    id: 'damsel',
    name: 'Doncella Azul',
    waterType: 'salada',
    temperament: 'agresivo',
    maxQuantity: 3,
    price: 4500,
    description: 'Brillante azul eléctrico. Muy territorial con sus congéneres.',
    incompatibleWith: ['clownfish', 'marine-angel', 'neon-goby', 'chromis'],
  },
  {
    id: 'marine-angel',
    name: 'Ángel Marino',
    waterType: 'salada',
    temperament: 'semiagresivo',
    maxQuantity: 2,
    price: 12000,
    description: 'Espectacular pez con franjas de colores. Necesita espacio y escondites.',
    incompatibleWith: ['damsel'],
  },
  {
    id: 'tang',
    name: 'Tang Azul',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 1,
    price: 15000,
    description: 'El famoso pez de aleta caudal amarilla. Necesita nadar mucho.',
    incompatibleWith: [],
  },
  {
    id: 'neon-goby',
    name: 'Gobio Neón',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 6,
    price: 3500,
    description: 'Pequeño limpiador con franja azul fluorescente. Muy activo.',
    incompatibleWith: ['damsel', 'lionfish'],
  },
  {
    id: 'mandarin',
    name: 'Pez Mandarina',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 2,
    price: 9000,
    description: 'Uno de los peces más coloridos del mundo. Dieta especializada.',
    incompatibleWith: ['lionfish'],
  },
  {
    id: 'lionfish',
    name: 'Pez León',
    waterType: 'salada',
    temperament: 'predador',
    maxQuantity: 1,
    price: 18000,
    description: 'Depredador de espinas venenosas. Solo puede coexistir con peces grandes.',
    incompatibleWith: ['clownfish', 'neon-goby', 'mandarin', 'chromis', 'damsel'],
  },
  {
    id: 'chromis',
    name: 'Chromis Verde',
    waterType: 'salada',
    temperament: 'pacifico',
    maxQuantity: 8,
    price: 2500,
    description: 'Pez de banco resistente y activo. Excelente para acuarios de arrecife.',
    incompatibleWith: ['lionfish', 'damsel'],
  },
]

// ─── Datos de iluminación ────────────────────────────────────────────────────

import type { Iluminacion, AccesorioOpcional, PeceraPrediseno } from './types'

export const ILUMINACIONES: Iluminacion[] = [
  {
    id: 'luz-basica',
    name: 'Luz Básica LED',
    tipo: 'LED',
    potencia: '10W',
    cobertura: 'hasta 40 cm',
    minLitros: 0,
    maxLitros: 30,
    price: 7500,
    descripcion: 'Iluminación LED de entrada para peceras nano. Bajo consumo.',
  },
  {
    id: 'luz-media',
    name: 'LED Full Spectrum',
    tipo: 'LED',
    potencia: '24W',
    cobertura: '40–80 cm',
    minLitros: 20,
    maxLitros: 100,
    price: 18500,
    descripcion: 'Espectro completo ideal para plantas y corales de bajo requerimiento.',
  },
  {
    id: 'luz-planted',
    name: 'LED Planted Plus',
    tipo: 'LED',
    potencia: '45W',
    cobertura: '60–120 cm',
    minLitros: 60,
    maxLitros: 200,
    price: 32000,
    descripcion: 'Alta intensidad para plantas exigentes y acuarios plantados densos.',
  },
  {
    id: 'luz-reef',
    name: 'LED Reef Pro',
    tipo: 'LED',
    potencia: '90W',
    cobertura: '80–150 cm',
    minLitros: 100,
    maxLitros: 350,
    price: 65000,
    descripcion: 'Control de espectro por canal. Ideal para acuarios de arrecife con corales SPS.',
  },
  {
    id: 'luz-t5',
    name: 'T5 HO Doble',
    tipo: 'T5',
    potencia: '2×39W',
    cobertura: '60–120 cm',
    minLitros: 60,
    maxLitros: 250,
    price: 28000,
    descripcion: 'Fluorescente T5 de alta salida. Buena penetración y color natural.',
  },
]

// ─── Datos de accesorios opcionales ─────────────────────────────────────────

export const ACCESORIOS_OPCIONALES: AccesorioOpcional[] = [
  {
    id: 'calentador',
    name: 'Calentador 150W',
    categoria: 'calefaccion',
    price: 12500,
    descripcion: 'Termocalentador sumergible con termostato ajustable. Para hasta 150L.',
  },
  {
    id: 'calentador-xl',
    name: 'Calentador 300W',
    categoria: 'calefaccion',
    price: 18000,
    descripcion: 'Para peceras de 150–300L. Con protección contra encendido en seco.',
  },
  {
    id: 'co2-kit',
    name: 'Kit CO₂ Básico',
    categoria: 'co2',
    price: 35000,
    descripcion: 'Sistema de CO₂ con botella recargable, regulador y difusor. Para plantas.',
  },
  {
    id: 'sustrato-planted',
    name: 'Sustrato Plantado',
    categoria: 'sustrato',
    price: 15000,
    descripcion: 'Sustrato nutritivo activo para acuarios plantados. Bolsa de 9 kg.',
  },
  {
    id: 'sustrato-marino',
    name: 'Arena Marina',
    categoria: 'sustrato',
    price: 12000,
    descripcion: 'Arena coralina de grano fino para acuarios de agua salada. 10 kg.',
  },
  {
    id: 'tapa',
    name: 'Tapa de Vidrio',
    categoria: 'proteccion',
    price: 8500,
    descripcion: 'Tapa de vidrio templado con bisagra. Reduce evaporación y protege los peces.',
  },
  {
    id: 'termometro',
    name: 'Termómetro Digital',
    categoria: 'monitoreo',
    price: 3500,
    descripcion: 'Termómetro LCD con sonda sumergible. Precisión ±0.1°C.',
  },
  {
    id: 'red-peces',
    name: 'Set de Redes',
    categoria: 'mantenimiento',
    price: 2500,
    descripcion: 'Set de 3 redes de diferentes tamaños para manejo de peces.',
  },
  {
    id: 'sifon',
    name: 'Sifón Limpiafondo',
    categoria: 'mantenimiento',
    price: 4500,
    descripcion: 'Sifón de limpieza de fondo con manguera de 1.5 m. Fácil de usar.',
  },
  {
    id: 'osmoinstalada',
    name: 'Osmosis Inversa (básica)',
    categoria: 'tratamiento-agua',
    price: 55000,
    descripcion: 'Sistema de purificación de agua. Esencial para agua salada y plantas exigentes.',
  },
]

// ─── Peceras prediseñadas ────────────────────────────────────────────────────

export const PECERAS_PREDISENO: PeceraPrediseno[] = [
  {
    id: 'starter-dulce',
    name: 'Starter Agua Dulce',
    litros: 60,
    dimensions: '60 × 35 × 35 cm',
    price: 85000,
    waterType: ['dulce'],
    descripcion: 'Kit completo para comenzar en el hobby. Listo para montar.',
    incluye: ['Pecera 60L', 'Filtro interno', 'Luz LED básica', 'Calentador 150W', 'Sustrato natural', 'Tapa'],
  },
  {
    id: 'planted-tank',
    name: 'Planted Tank 120L',
    litros: 120,
    dimensions: '90 × 40 × 40 cm',
    price: 185000,
    waterType: ['dulce'],
    descripcion: 'Configuración optimizada para acuarios plantados densos con CO₂.',
    incluye: ['Pecera 120L', 'Filtro externo M', 'LED Planted Plus', 'Kit CO₂', 'Sustrato plantado', 'Calentador 150W'],
  },
  {
    id: 'reef-starter',
    name: 'Reef Starter 200L',
    litros: 200,
    dimensions: '120 × 50 × 40 cm',
    price: 320000,
    waterType: ['salada'],
    descripcion: 'Todo lo necesario para un arrecife de agua salada con corales blandos.',
    incluye: ['Pecera 200L', 'Sump', 'LED Reef Pro', 'Arena marina', 'Skimmer', 'Bomba de movimiento', 'Tapa'],
  },
  {
    id: 'goldfish-bowl',
    name: 'Pecera Dorada 80L',
    litros: 80,
    dimensions: '75 × 35 × 35 cm',
    price: 95000,
    waterType: ['dulce'],
    descripcion: 'Ideal para peces dorados o ciclidos. Filtración potente incluida.',
    incluye: ['Pecera 80L', 'Filtro externo M', 'Luz LED full spectrum', 'Sustrato natural', 'Tapa', 'Termómetro'],
  },
]
