import type { Producto } from './types'

export const PRECIO_MIN = 1500
export const PRECIO_MAX = 85000

export const formatColones = (precio: number): string =>
  new Intl.NumberFormat('es-CR', {
    style: 'currency',
    currency: 'CRC',
    minimumFractionDigits: 0,
  }).format(precio)

export const PRODUCTOS: Producto[] = [
  // --- Agua dulce: peces ---
  {
    id: 'neon-tetra',
    nombre: 'Neón Tetra',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 2500,
    imagen: '/NeonTetra.png',
    marca: 'Agregar Marca',
    descripcion: 'Pequeño pez de colores vibrantes con franja azul neón y vientre rojo. Ideal en cardúmenes.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'facil',
    destacado: true,
  },
  {
    id: 'betta',
    nombre: 'Betta Splendens',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 8500,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Conocido como pez luchador siamés. Sus aletas largas y colores intensos lo hacen inconfundible.',
    disponible: true,
    temperamento: 'agresivo',
    nivelCuidado: 'facil',
    destacado: true,
  },
  {
    id: 'guppy-multicolor',
    nombre: 'Guppy Multicolor',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 1800,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Uno de los peces de acuario más populares del mundo. Fácil de reproducir y muy resistente.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'facil',
    destacado: false,
  },
  {
    id: 'corydora-bronze',
    nombre: 'Corydora Bronze',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 3200,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Pez de fondo que ayuda a limpiar el sustrato. Tranquilo y social, mejor en grupos de 6 o más.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'facil',
    destacado: false,
  },
  {
    id: 'molly-negro',
    nombre: 'Molly Negro',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 2200,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Pez robusto de color negro azabache. Adaptable a diferentes durezas de agua.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'facil',
    destacado: false,
  },
  {
    id: 'platy-sunset',
    nombre: 'Platy Sunset',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 2800,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Pez vivíparo con tonos anaranjados degradados que recuerdan al atardecer. Muy activo.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'facil',
    destacado: false,
  },
  {
    id: 'oscar',
    nombre: 'Pez Óscar',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 12000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Cíclido de gran tamaño con personalidad marcada. Reconoce a su dueño y acepta comida a mano.',
    disponible: true,
    temperamento: 'agresivo',
    nivelCuidado: 'intermedio',
    destacado: true,
  },
  {
    id: 'disco',
    nombre: 'Pez Disco',
    categoria: 'pez-dulce',
    tipoAgua: 'dulce',
    precio: 35000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'El rey del acuario tropical. Colores espectaculares y comportamiento social único.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'avanzado',
    destacado: true,
  },
  // --- Agua salada: peces ---
  {
    id: 'pez-payaso',
    nombre: 'Pez Payaso',
    categoria: 'pez-salado',
    tipoAgua: 'salada',
    precio: 18000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Inmortalizado en la cultura popular. Vive en simbiosis con las anémonas de mar.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'intermedio',
    destacado: true,
  },
  {
    id: 'tang-azul',
    nombre: 'Tang Azul',
    categoria: 'pez-salado',
    tipoAgua: 'salada',
    precio: 42000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Pez de arrecife de azul intenso con aleta caudal amarilla. Requiere acuarios de gran volumen.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'avanzado',
    destacado: true,
  },
  {
    id: 'pez-leon',
    nombre: 'Pez León',
    categoria: 'pez-salado',
    tipoAgua: 'salada',
    precio: 55000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Espectacular pero venenoso. Sus aletas contienen espinas urticantes. Solo para expertos.',
    disponible: false,
    temperamento: 'solitario',
    nivelCuidado: 'avanzado',
    destacado: false,
  },
  {
    id: 'pez-mariposa',
    nombre: 'Pez Mariposa Bandera',
    categoria: 'pez-salado',
    tipoAgua: 'salada',
    precio: 32000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Elegante pez de arrecife con llamativos patrones geométricos en blanco y negro.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'avanzado',
    destacado: false,
  },
  {
    id: 'pez-angel-emperador',
    nombre: 'Pez Ángel Emperador',
    categoria: 'pez-salado',
    tipoAgua: 'salada',
    precio: 68000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Una de las especies más bellas del océano. Bandas horizontales en azul, amarillo y blanco.',
    disponible: true,
    temperamento: 'agresivo',
    nivelCuidado: 'avanzado',
    destacado: true,
  },
  // --- Invertebrados ---
  {
    id: 'camaron-limpiador',
    nombre: 'Camarón Limpiador',
    categoria: 'invertebrado',
    tipoAgua: 'salada',
    precio: 15000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Servicio de limpieza natural para tu arrecife. Elimina parásitos de otros peces.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'intermedio',
    destacado: false,
  },
  {
    id: 'estrella-mar-roja',
    nombre: 'Estrella de Mar Roja',
    categoria: 'invertebrado',
    tipoAgua: 'salada',
    precio: 22000,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Estrella de cinco brazos de rojo intenso. Limpiadora del sustrato arenoso del arrecife.',
    disponible: false,
    temperamento: 'solitario',
    nivelCuidado: 'avanzado',
    destacado: false,
  },
  // --- Plantas acuáticas ---
  {
    id: 'anubias-nana',
    nombre: 'Anubias Nana',
    categoria: 'planta-acuatica',
    tipoAgua: 'dulce',
    precio: 4500,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Planta de crecimiento lento y muy resistente. No necesita CO₂ adicional ni sustrato especial.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'facil',
    destacado: false,
  },
  {
    id: 'helecho-java',
    nombre: 'Helecho de Java',
    categoria: 'planta-acuatica',
    tipoAgua: 'dulce',
    precio: 5800,
    imagen: 'https://placehold.co/300x300',
    marca: 'Agregar Marca',
    descripcion: 'Se fija a rocas y troncos sin necesidad de sustrato. Perfecta para acuarios de principiantes.',
    disponible: true,
    temperamento: 'pacifico',
    nivelCuidado: 'facil',
    destacado: true,
  },
]
